<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>

        <Nullable>disable</Nullable>

        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

        <TargetFramework>net10.0</TargetFramework>

        <Company>StugSoft</Company>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="NUnit" />
        <PackageReference Include="NUnit3TestAdapter" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Sphere10.HashLib4CSharp\Sphere10.HashLib4CSharp.csproj" />
    </ItemGroup>

</Project>
