name: Build
on: push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTIONS: true
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.0-rc.1
      - name: Build Hydrogen solution
        run: dotnet build "./src/Hydrogen (CrossPlatform).sln" --verbosity minimal
      - name: Run tests
        run: dotnet test "./src/Hydrogen (CrossPlatform).sln" --verbosity minimal
